pull_request_rules:
  - name: Automatic merge on approval and successful trivy-scan
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
        strict_method: merge
      delete_head_branch: {}
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=trivy-scan
  - name: Automatic merge PRs with auto-merge label upon successful trivy-scan
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
        strict_method: merge
      delete_head_branch: {}
    conditions:
      - label=auto-merge
      - status-success=trivy-scan
  - name: Merge pull requests from dependabot if CI passes
    conditions:
      - author=dependabot[bot]
      - status-success=trivy-scan
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
        strict_method: merge